'use strict';

// [name, ISO code, currency, currency symbol, has office, phone code]
module.exports = [
  ['Afghanistan', 'AF', 'AFN', '؋', false, '+93'],
  ['Åland Islands', 'AX', 'EUR', '€', false, '+358'],
  ['Albania', 'AL', 'ALL', 'L', false, '+355'],
  ['Algeria', 'DZ', 'DZD', 'د.ج', false, '+213'],
  ['American Samoa', 'AS', 'USD', '$', false, '+1'],
  ['Andorra', 'AD', 'EUR', '€', false, '+376'],
  ['Angola', 'AO', 'AOA', 'Kz', false, '+244'],
  ['Anguilla', 'AI', 'XCD', '$', false, '+1'],
  ['Antarctica', 'AQ', 'USD', '$', false, '+672'],
  ['Antigua and Barbuda', 'AG', 'XCD', '$', false, '+1'],
  ['Argentina', 'AR', 'ARS', '$', false, '+54'],
  ['Armenia', 'AM', 'AMD', '֏', false, '+374'],
  ['Aruba', 'AW', 'AWG', 'ƒ', false, '+297'],
  ['Australia', 'AU', 'AUD', '$', false, '+61'],
  ['Austria', 'AT', 'EUR', '€', false, '+43'],
  ['Azerbaijan', 'AZ', 'AZN', '₼', false, '+994'],
  ['Bahamas', 'BS', 'BSD', '$', false, '+1'],
  ['Bahrain', 'BH', 'BHD', '.د.ب', false, '+973'],
  ['Bangladesh', 'BD', 'BDT', '৳', false, '+880'],
  ['Barbados', 'BB', 'BBD', '$', false, '+1'],
  ['Belarus', 'BY', 'BYN', 'Br', false, '+375'],
  ['Belgium', 'BE', 'EUR', '€', false, '+32'],
  ['Belize', 'BZ', 'BZD', '$', false, '+501'],
  ['Benin', 'BJ', 'XOF', 'CFA', false, '+229'],
  ['Bermuda', 'BM', 'BMD', '$', false, '+1'],
  ['Bhutan', 'BT', 'BTN', 'Nu.', false, '+975'],
  ['Bolivia', 'BO', 'BOB', 'Bs.', false, '+591'],
  ['Bosnia and Herzegovina', 'BA', 'BAM', 'KM', false, '+387'],
  ['Botswana', 'BW', 'BWP', 'P', true, '+267'],
  ['Bouvet Island', 'BV', 'NOK', 'kr', false, '+47'],
  ['Brazil', 'BR', 'BRL', 'R$', false, '+55'],
  ['British Indian Ocean Territory', 'IO', 'USD', '$', false, '+246'],
  ['British Virgin Islands', 'VG', 'USD', '$', false, '+1'],
  ['Brunei', 'BN', 'BND', '$', false, '+673'],
  ['Bulgaria', 'BG', 'BGN', 'лв', false, '+359'],
  ['Burkina Faso', 'BF', 'XOF', 'CFA', false, '+226'],
  ['Burundi', 'BI', 'BIF', 'FBu', true, '+257'],
  ['Cabo Verde', 'CV', 'CVE', '$', false, '+238'],
  ['Cambodia', 'KH', 'KHR', '៛', false, '+855'],
  ['Cameroon', 'CM', 'XAF', 'FCFA', false, '+237'],
  ['Canada', 'CA', 'CAD', '$', false, '+1'],
  ['Cayman Islands', 'KY', 'KYD', '$', false, '+1'],
  ['Central African Republic', 'CF', 'XAF', 'FCFA', false, '+236'],
  ['Chad', 'TD', 'XAF', 'FCFA', false, '+235'],
  ['Chile', 'CL', 'CLP', '$', false, '+56'],
  ['China', 'CN', 'CNY', '¥', false, '+86'],
  ['Christmas Island', 'CX', 'AUD', '$', false, '+61'],
  ['Cocos (Keeling) Islands', 'CC', 'AUD', '$', false, '+61'],
  ['Colombia', 'CO', 'COP', '$', false, '+57'],
  ['Comoros', 'KM', 'KMF', 'CF', false, '+269'],
  ['Congo', 'CG', 'XAF', 'FCFA', false, '+242'],
  ['Cook Islands', 'CK', 'NZD', '$', false, '+682'],
  ['Costa Rica', 'CR', 'CRC', '₡', false, '+506'],
  ["Côte d'Ivoire", 'CI', 'XOF', 'CFA', true, '+225'],
  ['Croatia', 'HR', 'EUR', '€', false, '+385'],
  ['Cuba', 'CU', 'CUP', '$', false, '+53'],
  ['Curaçao', 'CW', 'ANG', 'ƒ', false, '+599'],
  ['Cyprus', 'CY', 'EUR', '€', false, '+357'],
  ['Czechia', 'CZ', 'CZK', 'Kč', false, '+420'],
  ['Democratic Republic of the Congo', 'CD', 'USD', 'USD', true, '+243'],
  ['Denmark', 'DK', 'DKK', 'kr', false, '+45'],
  ['Djibouti', 'DJ', 'DJF', 'Fdj', false, '+253'],
  ['Dominica', 'DM', 'XCD', '$', false, '+1'],
  ['Dominican Republic', 'DO', 'DOP', '$', false, '+1'],
  ['Ecuador', 'EC', 'USD', '$', false, '+593'],
  ['Egypt', 'EG', 'EGP', '£', false, '+20'],
  ['El Salvador', 'SV', 'USD', '$', false, '+503'],
  ['Equatorial Guinea', 'GQ', 'XAF', 'FCFA', false, '+240'],
  ['Eritrea', 'ER', 'ERN', 'Nfk', false, '+291'],
  ['Estonia', 'EE', 'EUR', '€', false, '+372'],
  ['Eswatini', 'SZ', 'SZL', 'L', false, '+268'],
  ['Ethiopia', 'ET', 'ETB', 'Br', false, '+251'],
  ['Falkland Islands', 'FK', 'FKP', '£', false, '+500'],
  ['Faroe Islands', 'FO', 'DKK', 'kr', false, '+298'],
  ['Fiji', 'FJ', 'FJD', '$', false, '+679'],
  ['Finland', 'FI', 'EUR', '€', false, '+358'],
  ['France', 'FR', 'EUR', '€', false, '+33'],
  ['French Guiana', 'GF', 'EUR', '€', false, '+594'],
  ['French Polynesia', 'PF', 'XPF', '₣', false, '+689'],
  ['French Southern Territories', 'TF', 'EUR', '€', false, '+262'],
  ['Gabon', 'GA', 'XAF', 'FCFA', false, '+241'],
  ['Gambia', 'GM', 'GMD', 'D', false, '+220'],
  ['Georgia', 'GE', 'GEL', '₾', false, '+995'],
  ['Germany', 'DE', 'EUR', '€', false, '+49'],
  ['Ghana', 'GH', 'GHS', '₵', false, '+233'],
  ['Gibraltar', 'GI', 'GIP', '£', false, '+350'],
  ['Greece', 'GR', 'EUR', '€', false, '+30'],
  ['Greenland', 'GL', 'DKK', 'kr', false, '+299'],
  ['Grenada', 'GD', 'XCD', '$', false, '+1'],
  ['Guadeloupe', 'GP', 'EUR', '€', false, '+590'],
  ['Guam', 'GU', 'USD', '$', false, '+1'],
  ['Guatemala', 'GT', 'GTQ', 'Q', false, '+502'],
  ['Guernsey', 'GG', 'GBP', '£', false, '+44'],
  ['Guinea', 'GN', 'GNF', 'FG', false, '+224'],
  ['Guinea-Bissau', 'GW', 'XOF', 'CFA', false, '+245'],
  ['Guyana', 'GY', 'GYD', '$', false, '+592'],
  ['Haiti', 'HT', 'HTG', 'G', false, '+509'],
  ['Heard Island and McDonald Islands', 'HM', 'AUD', '$', false, '+672'],
  ['Honduras', 'HN', 'HNL', 'L', false, '+504'],
  ['Hong Kong', 'HK', 'HKD', '$', false, '+852'],
  ['Hungary', 'HU', 'HUF', 'Ft', false, '+36'],
  ['Iceland', 'IS', 'ISK', 'kr', false, '+354'],
  ['India', 'IN', 'INR', '₹', false, '+91'],
  ['Indonesia', 'ID', 'IDR', 'Rp', false, '+62'],
  ['Iran', 'IR', 'IRR', '﷼', false, '+98'],
  ['Iraq', 'IQ', 'IQD', 'ع.د', false, '+964'],
  ['Ireland', 'IE', 'EUR', '€', false, '+353'],
  ['Isle of Man', 'IM', 'GBP', '£', false, '+44'],
  ['Israel', 'IL', 'ILS', '₪', false, '+972'],
  ['Italy', 'IT', 'EUR', '€', false, '+39'],
  ['Jamaica', 'JM', 'JMD', '$', false, '+1'],
  ['Japan', 'JP', 'JPY', '¥', false, '+81'],
  ['Jersey', 'JE', 'GBP', '£', false, '+44'],
  ['Jordan', 'JO', 'JOD', 'د.ا', false, '+962'],
  ['Kazakhstan', 'KZ', 'KZT', '₸', false, '+7'],
  ['Kenya', 'KE', 'KES', 'KSh', true, '+254'],
  ['Kiribati', 'KI', 'AUD', '$', false, '+686'],
  ['Kuwait', 'KW', 'KWD', 'د.ك', false, '+965'],
  ['Kyrgyzstan', 'KG', 'KGS', 'с', false, '+996'],
  ['Laos', 'LA', 'LAK', '₭', false, '+856'],
  ['Latvia', 'LV', 'EUR', '€', false, '+371'],
  ['Lebanon', 'LB', 'LBP', 'ل.ل', false, '+961'],
  ['Lesotho', 'LS', 'LSL', 'L', true, '+266'],
  ['Liberia', 'LR', 'LRD', '$', false, '+231'],
  ['Libya', 'LY', 'LYD', 'ل.د', false, '+218'],
  ['Liechtenstein', 'LI', 'CHF', 'Fr.', false, '+423'],
  ['Lithuania', 'LT', 'EUR', '€', false, '+370'],
  ['Luxembourg', 'LU', 'EUR', '€', false, '+352'],
  ['Macao', 'MO', 'MOP', 'P', false, '+853'],
  ['Madagascar', 'MG', 'MGA', 'Ar', false, '+261'],
  ['Malawi', 'MW', 'MWK', 'MK', false, '+265'],
  ['Malaysia', 'MY', 'MYR', 'RM', false, '+60'],
  ['Maldives', 'MV', 'MVR', '.ރ', false, '+960'],
  ['Mali', 'ML', 'XOF', 'CFA', false, '+223'],
  ['Malta', 'MT', 'EUR', '€', false, '+356'],
  ['Marshall Islands', 'MH', 'USD', '$', false, '+692'],
  ['Martinique', 'MQ', 'EUR', '€', false, '+596'],
  ['Mauritania', 'MR', 'MRU', 'UM', false, '+222'],
  ['Mauritius', 'MU', 'MUR', '₨', false, '+230'],
  ['Mayotte', 'YT', 'EUR', '€', false, '+262'],
  ['Mexico', 'MX', 'MXN', '$', false, '+52'],
  ['Micronesia', 'FM', 'USD', '$', false, '+691'],
  ['Moldova', 'MD', 'MDL', 'L', false, '+373'],
  ['Monaco', 'MC', 'EUR', '€', false, '+377'],
  ['Mongolia', 'MN', 'MNT', '₮', false, '+976'],
  ['Montenegro', 'ME', 'EUR', '€', false, '+382'],
  ['Montserrat', 'MS', 'XCD', '$', false, '+1'],
  ['Morocco', 'MA', 'MAD', 'د.م.', false, '+212'],
  ['Mozambique', 'MZ', 'MZN', 'MT', true, '+258'],
  ['Myanmar', 'MM', 'MMK', 'Ks', false, '+95'],
  ['Namibia', 'NA', 'NAD', '$', true, '+264'],
  ['Nauru', 'NR', 'AUD', '$', false, '+674'],
  ['Nepal', 'NP', 'NPR', '₨', false, '+977'],
  ['Netherlands', 'NL', 'EUR', '€', false, '+31'],
  ['New Caledonia', 'NC', 'XPF', '₣', false, '+687'],
  ['New Zealand', 'NZ', 'NZD', '$', false, '+64'],
  ['Nicaragua', 'NI', 'NIO', 'C$', false, '+505'],
  ['Niger', 'NE', 'XOF', 'CFA', false, '+227'],
  ['Nigeria', 'NG', 'NGN', '₦', true, '+234'],
  ['Niue', 'NU', 'NZD', '$', false, '+683'],
  ['Norfolk Island', 'NF', 'AUD', '$', false, '+672'],
  ['North Korea', 'KP', 'KPW', '₩', false, '+850'],
  ['North Macedonia', 'MK', 'MKD', 'ден', false, '+389'],
  ['Northern Mariana Islands', 'MP', 'USD', '$', false, '+1'],
  ['Norway', 'NO', 'NOK', 'kr', false, '+47'],
  ['Oman', 'OM', 'OMR', 'ر.ع.', false, '+968'],
  ['Pakistan', 'PK', 'PKR', '₨', false, '+92'],
  ['Palau', 'PW', 'USD', '$', false, '+680'],
  ['Palestine', 'PS', 'ILS', '₪', false, '+970'],
  ['Panama', 'PA', 'PAB', 'B/.', false, '+507'],
  ['Papua New Guinea', 'PG', 'PGK', 'K', true, '+675'],
  ['Paraguay', 'PY', 'PYG', '₲', false, '+595'],
  ['Peru', 'PE', 'PEN', 'S/.', false, '+51'],
  ['Philippines', 'PH', 'PHP', '₱', true, '+63'],
  ['Pitcairn', 'PN', 'NZD', '$', false, '+64'],
  ['Poland', 'PL', 'PLN', 'zł', false, '+48'],
  ['Portugal', 'PT', 'EUR', '€', false, '+351'],
  ['Puerto Rico', 'PR', 'USD', '$', false, '+1'],
  ['Qatar', 'QA', 'QAR', 'ر.ق', false, '+974'],
  ['Réunion', 'RE', 'EUR', '€', false, '+262'],
  ['Romania', 'RO', 'RON', 'lei', false, '+40'],
  ['Russia', 'RU', 'RUB', '₽', false, '+7'],
  ['Rwanda', 'RW', 'RWF', 'FRw', true, '+250'],
  ['Samoa', 'WS', 'WST', 'T', false, '+685'],
  ['San Marino', 'SM', 'EUR', '€', false, '+378'],
  ['São Tomé and Príncipe', 'ST', 'STN', 'Db', false, '+239'],
  ['Saudi Arabia', 'SA', 'SAR', 'ر.س', false, '+966'],
  ['Senegal', 'SN', 'XOF', 'CFA', false, '+221'],
  ['Serbia', 'RS', 'RSD', 'дин.', false, '+381'],
  ['Seychelles', 'SC', 'SCR', '₨', false, '+248'],
  ['Sierra Leone', 'SL', 'SLE', 'Le', false, '+232'],
  ['Singapore', 'SG', 'SGD', '$', false, '+65'],
  ['Sint Maarten', 'SX', 'ANG', 'ƒ', false, '+1'],
  ['Slovakia', 'SK', 'EUR', '€', false, '+421'],
  ['Slovenia', 'SI', 'EUR', '€', false, '+386'],
  ['Solomon Islands', 'SB', 'SBD', '$', false, '+677'],
  ['Somalia', 'SO', 'SOS', 'Sh.So.', false, '+252'],
  ['South Africa', 'ZA', 'ZAR', 'R', true, '+27'],
  ['South Georgia and the South Sandwich Islands', 'GS', 'GBP', '£', false, '+500'],
  ['South Korea', 'KR', 'KRW', '₩', false, '+82'],
  ['South Sudan', 'SS', 'SSP', '£', true, '+211'],
  ['Spain', 'ES', 'EUR', '€', false, '+34'],
  ['Sri Lanka', 'LK', 'LKR', 'Rs', false, '+94'],
  ['Sudan', 'SD', 'SDG', 'ج.س.', false, '+249'],
  ['Suriname', 'SR', 'SRD', '$', false, '+597'],
  ['Svalbard and Jan Mayen', 'SJ', 'NOK', 'kr', false, '+47'],
  ['Sweden', 'SE', 'SEK', 'kr', false, '+46'],
  ['Switzerland', 'CH', 'CHF', 'Fr.', true, '+41'],
  ['Syria', 'SY', 'SYP', '£', false, '+963'],
  ['Taiwan', 'TW', 'TWD', '$', false, '+886'],
  ['Tajikistan', 'TJ', 'TJS', 'ЅМ', false, '+992'],
  ['Tanzania', 'TZ', 'TZS', 'TSh', true, '+255'],
  ['Thailand', 'TH', 'THB', '฿', false, '+66'],
  ['Timor-Leste', 'TL', 'USD', '$', false, '+670'],
  ['Togo', 'TG', 'XOF', 'CFA', false, '+228'],
  ['Tokelau', 'TK', 'NZD', '$', false, '+690'],
  ['Tonga', 'TO', 'TOP', 'T$', false, '+676'],
  ['Trinidad and Tobago', 'TT', 'TTD', '$', false, '+1'],
  ['Tunisia', 'TN', 'TND', 'د.ت', false, '+216'],
  ['Turkey', 'TR', 'TRY', '₺', false, '+90'],
  ['Turkmenistan', 'TM', 'TMT', 'T', false, '+993'],
  ['Turks and Caicos Islands', 'TC', 'USD', '$', false, '+1'],
  ['Tuvalu', 'TV', 'AUD', '$', false, '+688'],
  ['U.S. Virgin Islands', 'VI', 'USD', '$', false, '+1'],
  ['Uganda', 'UG', 'UGX', 'UGX', true, '+256'],
  ['Ukraine', 'UA', 'UAH', '₴', false, '+380'],
  ['United Arab Emirates', 'AE', 'AED', 'د.إ', false, '+971'],
  ['United Kingdom', 'GB', 'GBP', '£', false, '+44'],
  ['United States', 'US', 'USD', '$', false, '+1'],
  ['United States Minor Outlying Islands', 'UM', 'USD', '$', false, '+1'],
  ['Uruguay', 'UY', 'UYU', '$', false, '+598'],
  ['Uzbekistan', 'UZ', 'UZS', 'soʻm', false, '+998'],
  ['Vanuatu', 'VU', 'VUV', 'VT', false, '+678'],
  ['Vatican City', 'VA', 'EUR', '€', false, '+39'],
  ['Venezuela', 'VE', 'VES', 'Bs.S', false, '+58'],
  ['Vietnam', 'VN', 'VND', '₫', false, '+84'],
  ['Wallis and Futuna', 'WF', 'XPF', '₣', false, '+681'],
  ['Western Sahara', 'EH', 'MAD', 'د.م.', false, '+212'],
  ['Yemen', 'YE', 'YER', '﷼', false, '+967'],
  ['Zambia', 'ZM', 'ZMW', 'ZK', true, '+260'],
  ['Zimbabwe', 'ZW', 'ZWG', 'ZiG', true, '+263']
];
