'use strict';

const J = (...parts) => parts.join('');

module.exports = [
  {
    slug: "drb",
    title: "Direct Referral Bonus (DRB)",
    icon: "🤝",
    shortDescription: "Earn a commission every time someone you personally introduce joins and activates a package.",
    longDescription: J(
    "The Direct Referral Bonus (DRB) is the commission you earn when someone joins the business through y",
    "our personal invitation and activates a package under you. It is a reward for directly introducing n",
    "ew people to the opportunity. The amount depends on the package chosen — higher packages generate hi",
    "gher bonuses. There is no limit to the number of people you can refer, so the more active referrals ",
    "you have, the greater your total potential earnings."
  ),
    order: 1,
    active: true
  },
  {
    slug: "msb",
    title: "Matched Sales Bonus (MSB) / Pairing Commission",
    icon: "🔁",
    shortDescription: "Earn every time one person joins your left side and one joins your right side — automatically matched by the system.",
    longDescription: J(
    "AIM Global uses a Binary Network System. When you register, you get two sides — left and right. Ever",
    "y time a new member joins your left and a new member joins your right, the system automatically dete",
    "cts this and issues you a Matched Sales Bonus (pairing). This process duplicates downwards infinitel",
    "y. Even people you did not personally recruit can trigger pairings if they are placed in your organi",
    "zation. The global package gives 1 pair per match, up to 15 pairs for MegaVerse."
  ),
    order: 2,
    active: true
  },
  {
    slug: "unilevel",
    title: "Unilevel Commission (5%–10%)",
    icon: "📊",
    shortDescription: "Earn 5% sponsor commission and 5% placement commission on product purchases by your downline up to 10 levels deep.",
    longDescription: J(
    "Every time your downline purchases a product, you earn a 5% Sponsor Commission from your direct refe",
    "rrals and another 5% Placement Commission from your 1st up to 10th level in the organization. Each p",
    "roduct is assigned a fixed commissional point which determines the 5% unilevel commission earned on ",
    "every purchase. This system uses Dynamic Compression — if any level within your 10 levels is inactiv",
    "e, the next active level moves up, ensuring you never lose commissions to inactive distributors."
  ),
    order: 3,
    active: true
  },
  {
    slug: "stairstep",
    title: "Stairstep Commission (10%–30%)",
    icon: "🪜",
    shortDescription: "Earn additional commissions based on your rank — 10% for Silver Executive, 20% for Gold Executive, 30% for Global Ambassador.",
    longDescription: J(
    "The Stairstep System rewards rank promotion through product reorders. This income is added to your U",
    "nilevel commission received monthly. Silver Executives earn an additional 10% stairstep commission. ",
    "Gold Executives earn 20% additional. Global Ambassadors earn 30% additional. Ranks are achieved thro",
    "ugh group accumulation of positional points — no demotion, no pass-up, no time frame, no reversion."
  ),
    order: 4,
    active: true
  },
  {
    slug: "royalty",
    title: "Royalty Bonus (2%)",
    icon: "👑",
    shortDescription: "As a Global Ambassador, earn 2% rebates based on Group Reorder Points down to your 5th level Global Ambassador downlines.",
    longDescription: J(
    "The Royalty Bonus is exclusively available to Global Ambassadors. You earn 2% rebates based on Group",
    " Reorder Points generated by your downlines who are also Global Ambassadors, up to 5 levels deep. Th",
    "is is a powerful passive income stream that rewards leadership development within your organization."
  ),
    order: 5,
    active: true
  },
  {
    slug: "profit-sharing",
    title: "Profit Sharing",
    icon: "🏦",
    shortDescription: "Elite Global Ambassadors receive a share of company profits on a yearly basis based on specific rank and activity requirements.",
    longDescription: J(
    "Profit Sharing is given to Elite Global Ambassadors on a yearly basis based on certain requirements ",
    "set by the company. This represents one of the highest levels of recognition and reward in the AIM G",
    "lobal compensation system, reflecting the company's commitment to sharing its success with top-perfo",
    "rming distributors."
  ),
    order: 6,
    active: true
  },
  {
    slug: "upp",
    title: "Uni Pay Plan (UPP)",
    icon: "💹",
    shortDescription: "AIM Global's unilevel income system where distributors earn commissions from product purchases and reorders made by their downlines up to multiple levels deep.",
    longDescription: J(
    "The Uni Pay Plan is AIM Global's unilevel income system where distributors earn commissions from pro",
    "duct purchases and reorders made by their direct and indirect downlines up to multiple levels deep. ",
    "The more active distributors and consumers in your organization, the bigger your monthly residual in",
    "come. This system ensures that product sales across your entire network contribute to your monthly e",
    "arnings."
  ),
    order: 7,
    active: true
  },
  {
    slug: "retail",
    title: "Retail Profit (25% Discount)",
    icon: "🛍️",
    shortDescription: "Earn direct profit by purchasing products at distributor price (25% discount) and selling them at retail price to customers.",
    longDescription: J(
    "Retail offers a 25% discount on all AIM Global products for distributors. This allows you to earn di",
    "rect profit by purchasing products at the distributor price and selling them at the full retail pric",
    "e to customers. While the business is not focused primarily on retail selling, this provides an addi",
    "tional immediate income stream alongside the residual and network-based earnings."
  ),
    order: 8,
    active: true
  },
];
